### PR TITLE
feat: add user model

### PR DESCRIPTION
**Pull request by greatislander**
Adds user model with login, registration, and email verification.

- [x] Localized routes and language switcher
- [x] User model and migrations
- [x] Login and registration views and controllers (via Fortify)
- [x] Dashboard view
- [x] User account admin and user settings views and controllers
- [x] Looseleaf styles for basic layout

### Testing

1. Create new Laravel application.
2. Follow README instructions (up to date in this PR) to add and install Hearth to the application.
3. Test:
    - User registration
    - Email verification
    - User account editing (name, email, password)
    - User account deletion
    - User settings management (changing default language)

### Additional Info

There's a lot in here and correspondingly lots of room to clean up and improve. I'd like to get this merged and then create a number of follow-up issues to iron out some of the details.

### Related Issues

- #9

### CODE REVIEW

**Comment by waharnum** [comment]
A quick first pass:

# Sails on Docker for Windows/WSL Notes

As we've discussed, using Sails via Docker for Windows/WSL2 works well, and is mostly seamless with these notes:
- commands that need to execute in the container context for dependencies that may be in the container but not the WSL environment should be run as follows: `sails npm install`
- to access the running app from Windows via the `APP_URL` defined in the `.env` file, you need to create an entry in the Windows host file like `127.0.0.1 eds-app.test` - https://docs.rackspace.com/support/how-to/modify-your-hosts-file has instructions for this

# Test Results

## User registration

With a clean install of Hearth, this creates the user but throws a `Swift_TransportException` "cannot send message without a sender address", and does not send the verification email.

After some Googling, I was able to resolve this by changing `MAIL_FROM_ADDRESS` in the `.env` file from a `null` value to `hearth@inclusivedesign.ca`. From what I can tell, it is only required that it be a validly formatted email address, but it needs to be present.

## Email verification

This worked once the issue mentioned above was resolved.

## User account editing (name, email, password)
- Able to log in and edit name and email via "Settings"
- Able to log in and change password via "Account"

## User account deletion
- Able to delete an account via "Account"

## User settings management (changing default language)
- Able to log in and change default language to `francais` via "Settings"

**Comment by greatislander** [comment]
> ## User registration
> With a clean install of Hearth, this creates the user but throws a `Swift_TransportException` "cannot send message without a sender address", and does not send the verification email.
> 
> After some Googling, I was able to resolve this by changing `MAIL_FROM_ADDRESS` in the `.env` file from a `null` value to `hearth@inclusivedesign.ca`. From what I can tell, it is only required that it be a validly formatted email address, but it needs to be present.

I've documented this requirement here: https://github.com/fluid-project/hearth/blob/95c2a5b74f7bc1c30759d494ae9050f9691bc05b/README.md#emails

**Comment by greatislander** [comment]
@waharnum Updated with a bit more boilerplate CSS to properly layout the navigation, login screen, etc.

**Comment by greatislander** [comment]
An issue I noticed while working on this: https://github.com/chinleung/laravel-multilingual-routes/issues/54

**Review by waharnum — APPROVED** [review]
I think with the new CSS and the addition to the documentation, this is good to be merged.

**Pull request merged**
