### PR TITLE
feat: add Checkbox and Checkboxes components (resolves #83)

### LINKED ISSUE #83: Add checkbox and checkboxes components
## Is your feature request related to a problem?

Like radio buttons (#35, #72), checkboxes need to be handled with their own component as you can't use `@if` within the markup of a Blade component and the `checked` attribute needs a conditional to determine whether or not it should be present.

## Describe the solution you'd like

Create an `<x-hearth-checkbox>` component for single checkboxes and an `<x-hearth-checkboxes>` component for groups of related checkboxes.

## Describe alternative solutions you've considered

Not applicable.

## Additional context or notes

Not applicable.

### PR DESCRIPTION
**Pull request by greatislander**
Adds a Checkbox component and a Checkboxes component for a group of related checkboxes.

### Testing

1. Create a new project with Hearth using this branch.
2. Test the `<x-hearth-checkbox>` and `<x-hearth-checkboxes>` (see docs: [Checkbox](https://github.com/fluid-project/hearth/wiki/Checkbox), [Checkboxes](https://github.com/fluid-project/hearth/wiki/Checkboxes)), including their usage with hints and validation.

### CODE REVIEW

**Comment by jobara** [comment]
@greatislander the [Checkboxes](https://github.com/fluid-project/hearth/wiki/Checkboxes) documentation appears to use radio buttons in the example.

**Comment by greatislander** [comment]
@jobara fixed, thanks for catching that

**Comment by jobara** [comment]
@greatislander I'm setting up a local Laravel project for testing and using Laravel Valet. I'm able to get the the Laravel project served with Valet. However, when adding my local instance of Hearth, I'm getting an error when trying to run `php artisan migrate`. 

```log
 Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = hearth_test and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:703
    699▕         // If an exception occurs when attempting to run a query, we'll format the error
    700▕         // message to include the bindings with SQL, which will make this exception a
    701▕         // lot more helpful to the developer instead of just the database's errors.
    702▕         catch (Exception $e) {
  ➜ 703▕             throw new QueryException(
    704▕                 $query, $this->prepareBindings($bindings), $e
    705▕             );
    706▕         }
    707▕     }

      +33 vendor frames 
  34  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

I've tried modifying the .env file to point at `localhost` and use `root`, in addition to using DBngin as described in [database](https://laravel.com/docs/8.x/valet#database) section of the Valet docs.

**Comment by greatislander** [comment]
@jobara: my Valet test environment uses this for DB configuration in `.env`:

```dotenv
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=hearth
DB_USERNAME=root
DB_PASSWORD=
```

**Comment by greatislander** [comment]
@jobara Turns out I do need this right away. I'm going to merge it but if you have a chance to test and open issues with any changes you identify that would be great.

**Pull request merged**
