### PR TITLE
feat: improve locale support (resolves #10)

### LINKED ISSUE #10: Improve multilingual features
- [ ] Interactive command line interface to allow a user to enable support for additional languages when installing Hearth
- [ ] Ensure that all language configuration data is loaded from `config/locales.php`

### PR DESCRIPTION
**Pull request by greatislander**
- [x] Interactive command line interface to allow a user to enable support for additional languages when installing Hearth
- [x] Ensure that all language configuration data is loaded from `config/locales.php`

### Testing

1. Install this branch as a composer dependency.
2. Run `php artisan hearth:install`.
3. Use interactive prompts to select as many additional locales as needed.
4. Verify that the `config/locales.php` file includes the newly-selected locales.
5. Verify that the new locales are able to be selected via the user settings page and appear in the language switcher.

### CODE REVIEW

**Comment by waharnum** [comment]
I had to update a new project's `composer.json` as follows to test the branch for the PR:

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/greatislander/hearth"
        }
    ],    
    "require": {
         ...
        "fluid-project/hearth": "dev-feat/multilingual-improvements",
        ...
    },
```

I assume this is all connected to how Composer thinks about dependencies (an area I am less than familiar with) and fills in Git upstream/downstream versions automatically via Github defaults.

**Comment by greatislander** [comment]
@waharnum Yes, that's correct. If you are installing a dependency that doesn't have a published version, rather than using a semver constraint you can reference any branch, tag, or commit by setting the version to: `dev-<reference>`.

For example:

- `dev-some-branch`
- `dev-7926352`
- `dev-1.0.0`

**Comment by waharnum** [comment]
> 
> 
> @waharnum Yes, that's correct. If you are installing a dependency that doesn't have a published version, rather than using a semver constraint you can reference any branch, tag, or commit by setting the version to: `dev-<reference>`.
> 
> For example:
> 
>     * `dev-some-branch`
> 
>     * `dev-7926352`
> 
>     * `dev-1.0.0`

The key was actually adding the `repositories` entry to reference your repository, while keeping the reference in `requires` to fluid-project.

`"greatislander/hearth": "dev-feat/multilingual-improvements"` did not work by itself, nor did `"fluid-project/hearth": "dev-feat/multilingual-improvements"`, but the second one worked following adding the `repository` entry.

**Comment by greatislander** [comment]
@waharnum Ah, right. That's because my repository has the same package name (`fluid-project/hearth`) so it needs to the repository configuration to point composer to the right place.

**Comment by waharnum** [comment]
Looks good to merge to me, I'll just note two things we might want for future improvements:

1. Consistent full language display (this might not be under our control, depending on the libraries used, but screenshot for example):

image

2. The "add locale" prompt should probably not default any response other than "yes" or "y" to a `false` - I think an explicit y/n response would be better.

**Comment by greatislander** [comment]
@waharnum If you'd like to open issues for those two that would be fantastic. I'll go ahead and merge.

**Pull request merged**
