### PR TITLE
feat: add organization, memberships and invitations (resolves #5)

### LINKED ISSUE #5: Add organization model, membership model, and invitation model (behind an install flag)

### PR DESCRIPTION
**Pull request by greatislander**
This PR adds an `Organization` model which users can join via a `Membership` model, and which users can be invited to join via an `Invitation` model. It also adds feature test stubs for users, two-factor authentication, and organizations, memberships and invitations.

### Testing

1. Install this branch with Composer.
2. Run the Hearth installer using the `--organizations` flag: `php artisan hearth:install --organizations`
3. Log in and navigate to `/en/organizations/create`.
4. Verify that you can create an organization.
5. Verify that you can edit your organization.
6. Verify that you can invite a new user to the organization.
7. Verify that you can register and log in as the new user and then accept the invitation.
8. Verify that if an organization has only one administrator, they cannot be removed from the organization.
9. Verify that non-administrative members of an organization cannot:
	- remove other users from the organization;
	- invite new users to the organization;
	- delete the organization.
10. Verify that administrators of an organization can delete the organization.

### Additional Information

- Blocked by #22.

### CODE REVIEW

**Comment by waharnum** [comment]
```
6. Verify that you can invite a new user to the organization.
7. Verify that you can register and log in as the new user and then accept the invitation.
```

For security / verification purposes, there should be a check that the email of the signed-in user clicking the invite link is the same as the one associated with the invited user. I was able to do the following at Steps 6/7:

* Send an organization invitation to `goodactor@gmail.com` (previously created account)
* Create an account for `badactor@gmail.com`
* While logged in as `badactor`, clicked the "accept invitation" invite link; this resulted in `goodactor` being added to the organization, but `goodactor` was not the logged in user.

**Comment by greatislander** [comment]
> For security / verification purposes, there should be a check that the email of the signed-in user clicking the invite link is the same as the one associated with the invited user.

@waharnum Thanks for catching this, I'm working on it!

**Comment by greatislander** [comment]
@waharnum Only a user logged in with a matching email should be able to accept an invitation now. Can you verify this on your end?

**Review by waharnum — APPROVED** [review]
As discussed, I'm good for this to go in now that the invite verification issue is fixed. We can open a separate issue to improve error handling in the "clicked the invite link without being the correct logged-in user case".

**Pull request merged**
